language: node_js

sudo: false

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

env:
  global:
    - GITHUB_REPO: github.com/plexpt/mirai-doc.git
before_install:
  - export TZ=Asia/Shanghai

script:
  - yarn run build

# 构建 同步， 拉doc分支， 强制，部署
after_success:
  - git config user.name "plexpt"
  - git config user.email "plexpt@gmail.com"
  - git clone -b gh-pages https://github.com/PlexPt/mirai-doc.git ./old-docs
  - cp -r ./old-docs/.git ./docs
  - cd ./docs
  - git add -A
  - git commit -m "auto deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git push --force --quiet "https://plexpt:${CI_TOKEN}@${GITHUB_REPO}" master:gh-pages
